version: '2'

services:
    web:
        image: nginx:1.17-alpine
        container_name: nginx01
        depends_on:
            - php
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        ports:
             - "80:80"
             - "443:443"
        volumes:
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/ssl/certs/trustedfox.ddns.net.pem:/etc/ssl/certs/trustedfox.ddns.net.pem:ro
            - ./nginx/ssl/private/trustedfox.ddns.net.pem:/etc/ssl/private/trustedfox.ddns.net.pem:ro
            - ./nginx/ssl/dhparam.pem:/etc/ssl/dhparam.pem:ro
            - ./nextcloud/data:/var/www/html/:ro
            - ./letsencrypt/conf:/etc/letsencrypt:ro
            - ./letsencrypt/www:/var/www/certbot:ro
        networks:
            - frontend

    php:
        image: nextcloud:production-fpm-alpine
        container_name: nextcloud01
        depends_on:
            - db
        environment:
            NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_USERNAME}
            NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_PASSWORD}
            MYSQL_HOST: ${DATABASE_HOST}
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_DOMAIN}
        volumes:
            - ./nextcloud/data:/var/www/html/
        networks:
            - frontend
            - backend

    db:
        image: hypriot/rpi-mysql:5.5
        container_name: mysql01
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
        volumes:
            - ./mysql/data:/var/lib/mysql 
        networks:
            - backend
    
    certbot:
        image: j0nnylester/certbot
        container_name: certbot01
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        volumes:
            - ./letsencrypt/conf:/etc/letsencrypt
            - ./letsencrypt/www:/var/www/certbot

networks:
    frontend:
    backend:
